bookkeeper_manager:
    resource: "@BookkeeperManagerBundle/Resources/config/routing.yml"
    prefix:   /book

bookkeeper_hello_world:
    resource: "@BookkeeperHelloWorldBundle/Resources/config/routing.yml"
    prefix:   /

